// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.8
// source: api/auction/service/v1/shop.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShopServiceCreateDeliveryAddress = "/auction.service.v1.ShopService/CreateDeliveryAddress"
const OperationShopServiceCreateDepositHold = "/auction.service.v1.ShopService/CreateDepositHold"
const OperationShopServiceDeleteDeliveryAddress = "/auction.service.v1.ShopService/DeleteDeliveryAddress"
const OperationShopServiceGetMyDepositHold = "/auction.service.v1.ShopService/GetMyDepositHold"
const OperationShopServiceGetMyUnifiedOrder = "/auction.service.v1.ShopService/GetMyUnifiedOrder"
const OperationShopServiceListDeliveryAddresses = "/auction.service.v1.ShopService/ListDeliveryAddresses"
const OperationShopServiceListMyFrequentStores = "/auction.service.v1.ShopService/ListMyFrequentStores"
const OperationShopServiceListMyUnifiedOrders = "/auction.service.v1.ShopService/ListMyUnifiedOrders"
const OperationShopServiceMockPayUnifiedOrder = "/auction.service.v1.ShopService/MockPayUnifiedOrder"
const OperationShopServiceSetDefaultDeliveryAddress = "/auction.service.v1.ShopService/SetDefaultDeliveryAddress"
const OperationShopServiceUpdateDeliveryAddress = "/auction.service.v1.ShopService/UpdateDeliveryAddress"

type ShopServiceHTTPServer interface {
	CreateDeliveryAddress(context.Context, *CreateDeliveryAddressRequest) (*CreateDeliveryAddressReply, error)
	CreateDepositHold(context.Context, *CreateDepositHoldRequest) (*CreateDepositHoldReply, error)
	DeleteDeliveryAddress(context.Context, *DeleteDeliveryAddressRequest) (*DeleteDeliveryAddressReply, error)
	GetMyDepositHold(context.Context, *GetMyDepositHoldRequest) (*GetMyDepositHoldReply, error)
	GetMyUnifiedOrder(context.Context, *GetMyUnifiedOrderRequest) (*GetMyUnifiedOrderReply, error)
	ListDeliveryAddresses(context.Context, *ListDeliveryAddressesRequest) (*ListDeliveryAddressesReply, error)
	ListMyFrequentStores(context.Context, *ListMyFrequentStoresRequest) (*ListMyFrequentStoresReply, error)
	ListMyUnifiedOrders(context.Context, *ListMyUnifiedOrdersRequest) (*ListMyUnifiedOrdersReply, error)
	MockPayUnifiedOrder(context.Context, *MockPayUnifiedOrderRequest) (*MockPayUnifiedOrderReply, error)
	SetDefaultDeliveryAddress(context.Context, *SetDefaultDeliveryAddressRequest) (*ListDeliveryAddressesReply, error)
	UpdateDeliveryAddress(context.Context, *UpdateDeliveryAddressRequest) (*UpdateDeliveryAddressReply, error)
}

func RegisterShopServiceHTTPServer(s *http.Server, srv ShopServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/shop/addresses", _ShopService_ListDeliveryAddresses0_HTTP_Handler(srv))
	r.POST("/api/shop/addresses", _ShopService_CreateDeliveryAddress0_HTTP_Handler(srv))
	r.PUT("/api/shop/addresses/{address_id}", _ShopService_UpdateDeliveryAddress0_HTTP_Handler(srv))
	r.DELETE("/api/shop/addresses/{address_id}", _ShopService_DeleteDeliveryAddress0_HTTP_Handler(srv))
	r.POST("/api/shop/addresses/{address_id}/default", _ShopService_SetDefaultDeliveryAddress0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/deposit-holds/mock-pay", _ShopService_CreateDepositHold0_HTTP_Handler(srv))
	r.GET("/api/lots/{lot_id}/deposit-holds/me", _ShopService_GetMyDepositHold0_HTTP_Handler(srv))
	r.GET("/api/orders/me", _ShopService_ListMyUnifiedOrders0_HTTP_Handler(srv))
	r.GET("/api/orders/me/frequent-stores", _ShopService_ListMyFrequentStores0_HTTP_Handler(srv))
	r.GET("/api/orders/{order_id}", _ShopService_GetMyUnifiedOrder0_HTTP_Handler(srv))
	r.POST("/api/orders/{order_id}/mock-pay", _ShopService_MockPayUnifiedOrder0_HTTP_Handler(srv))
}

func _ShopService_ListDeliveryAddresses0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDeliveryAddressesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListDeliveryAddresses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDeliveryAddresses(ctx, req.(*ListDeliveryAddressesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDeliveryAddressesReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_CreateDeliveryAddress0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDeliveryAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceCreateDeliveryAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDeliveryAddress(ctx, req.(*CreateDeliveryAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDeliveryAddressReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_UpdateDeliveryAddress0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDeliveryAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceUpdateDeliveryAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDeliveryAddress(ctx, req.(*UpdateDeliveryAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDeliveryAddressReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_DeleteDeliveryAddress0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDeliveryAddressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceDeleteDeliveryAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDeliveryAddress(ctx, req.(*DeleteDeliveryAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDeliveryAddressReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_SetDefaultDeliveryAddress0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetDefaultDeliveryAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceSetDefaultDeliveryAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDefaultDeliveryAddress(ctx, req.(*SetDefaultDeliveryAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDeliveryAddressesReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_CreateDepositHold0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDepositHoldRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceCreateDepositHold)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDepositHold(ctx, req.(*CreateDepositHoldRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDepositHoldReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_GetMyDepositHold0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMyDepositHoldRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceGetMyDepositHold)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMyDepositHold(ctx, req.(*GetMyDepositHoldRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMyDepositHoldReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_ListMyUnifiedOrders0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyUnifiedOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListMyUnifiedOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyUnifiedOrders(ctx, req.(*ListMyUnifiedOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMyUnifiedOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_ListMyFrequentStores0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyFrequentStoresRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListMyFrequentStores)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyFrequentStores(ctx, req.(*ListMyFrequentStoresRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMyFrequentStoresReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_GetMyUnifiedOrder0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMyUnifiedOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceGetMyUnifiedOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMyUnifiedOrder(ctx, req.(*GetMyUnifiedOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMyUnifiedOrderReply)
		return ctx.Result(200, reply)
	}
}

func _ShopService_MockPayUnifiedOrder0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MockPayUnifiedOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceMockPayUnifiedOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MockPayUnifiedOrder(ctx, req.(*MockPayUnifiedOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MockPayUnifiedOrderReply)
		return ctx.Result(200, reply)
	}
}

type ShopServiceHTTPClient interface {
	CreateDeliveryAddress(ctx context.Context, req *CreateDeliveryAddressRequest, opts ...http.CallOption) (rsp *CreateDeliveryAddressReply, err error)
	CreateDepositHold(ctx context.Context, req *CreateDepositHoldRequest, opts ...http.CallOption) (rsp *CreateDepositHoldReply, err error)
	DeleteDeliveryAddress(ctx context.Context, req *DeleteDeliveryAddressRequest, opts ...http.CallOption) (rsp *DeleteDeliveryAddressReply, err error)
	GetMyDepositHold(ctx context.Context, req *GetMyDepositHoldRequest, opts ...http.CallOption) (rsp *GetMyDepositHoldReply, err error)
	GetMyUnifiedOrder(ctx context.Context, req *GetMyUnifiedOrderRequest, opts ...http.CallOption) (rsp *GetMyUnifiedOrderReply, err error)
	ListDeliveryAddresses(ctx context.Context, req *ListDeliveryAddressesRequest, opts ...http.CallOption) (rsp *ListDeliveryAddressesReply, err error)
	ListMyFrequentStores(ctx context.Context, req *ListMyFrequentStoresRequest, opts ...http.CallOption) (rsp *ListMyFrequentStoresReply, err error)
	ListMyUnifiedOrders(ctx context.Context, req *ListMyUnifiedOrdersRequest, opts ...http.CallOption) (rsp *ListMyUnifiedOrdersReply, err error)
	MockPayUnifiedOrder(ctx context.Context, req *MockPayUnifiedOrderRequest, opts ...http.CallOption) (rsp *MockPayUnifiedOrderReply, err error)
	SetDefaultDeliveryAddress(ctx context.Context, req *SetDefaultDeliveryAddressRequest, opts ...http.CallOption) (rsp *ListDeliveryAddressesReply, err error)
	UpdateDeliveryAddress(ctx context.Context, req *UpdateDeliveryAddressRequest, opts ...http.CallOption) (rsp *UpdateDeliveryAddressReply, err error)
}

type ShopServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShopServiceHTTPClient(client *http.Client) ShopServiceHTTPClient {
	return &ShopServiceHTTPClientImpl{client}
}

func (c *ShopServiceHTTPClientImpl) CreateDeliveryAddress(ctx context.Context, in *CreateDeliveryAddressRequest, opts ...http.CallOption) (*CreateDeliveryAddressReply, error) {
	var out CreateDeliveryAddressReply
	pattern := "/api/shop/addresses"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceCreateDeliveryAddress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) CreateDepositHold(ctx context.Context, in *CreateDepositHoldRequest, opts ...http.CallOption) (*CreateDepositHoldReply, error) {
	var out CreateDepositHoldReply
	pattern := "/api/lots/{lot_id}/deposit-holds/mock-pay"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceCreateDepositHold))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) DeleteDeliveryAddress(ctx context.Context, in *DeleteDeliveryAddressRequest, opts ...http.CallOption) (*DeleteDeliveryAddressReply, error) {
	var out DeleteDeliveryAddressReply
	pattern := "/api/shop/addresses/{address_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceDeleteDeliveryAddress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) GetMyDepositHold(ctx context.Context, in *GetMyDepositHoldRequest, opts ...http.CallOption) (*GetMyDepositHoldReply, error) {
	var out GetMyDepositHoldReply
	pattern := "/api/lots/{lot_id}/deposit-holds/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceGetMyDepositHold))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) GetMyUnifiedOrder(ctx context.Context, in *GetMyUnifiedOrderRequest, opts ...http.CallOption) (*GetMyUnifiedOrderReply, error) {
	var out GetMyUnifiedOrderReply
	pattern := "/api/orders/{order_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceGetMyUnifiedOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) ListDeliveryAddresses(ctx context.Context, in *ListDeliveryAddressesRequest, opts ...http.CallOption) (*ListDeliveryAddressesReply, error) {
	var out ListDeliveryAddressesReply
	pattern := "/api/shop/addresses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListDeliveryAddresses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) ListMyFrequentStores(ctx context.Context, in *ListMyFrequentStoresRequest, opts ...http.CallOption) (*ListMyFrequentStoresReply, error) {
	var out ListMyFrequentStoresReply
	pattern := "/api/orders/me/frequent-stores"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListMyFrequentStores))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) ListMyUnifiedOrders(ctx context.Context, in *ListMyUnifiedOrdersRequest, opts ...http.CallOption) (*ListMyUnifiedOrdersReply, error) {
	var out ListMyUnifiedOrdersReply
	pattern := "/api/orders/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListMyUnifiedOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) MockPayUnifiedOrder(ctx context.Context, in *MockPayUnifiedOrderRequest, opts ...http.CallOption) (*MockPayUnifiedOrderReply, error) {
	var out MockPayUnifiedOrderReply
	pattern := "/api/orders/{order_id}/mock-pay"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceMockPayUnifiedOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) SetDefaultDeliveryAddress(ctx context.Context, in *SetDefaultDeliveryAddressRequest, opts ...http.CallOption) (*ListDeliveryAddressesReply, error) {
	var out ListDeliveryAddressesReply
	pattern := "/api/shop/addresses/{address_id}/default"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceSetDefaultDeliveryAddress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShopServiceHTTPClientImpl) UpdateDeliveryAddress(ctx context.Context, in *UpdateDeliveryAddressRequest, opts ...http.CallOption) (*UpdateDeliveryAddressReply, error) {
	var out UpdateDeliveryAddressReply
	pattern := "/api/shop/addresses/{address_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceUpdateDeliveryAddress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
