import type { EventType } from '../api/types';

export const REALTIME_EVENT = {
  ROOM_SNAPSHOT: 'AUCTION_EVENT_TYPE_ROOM_SNAPSHOT',
  LOT_CREATED: 'AUCTION_EVENT_TYPE_LOT_CREATED',
  LOT_STARTED: 'AUCTION_EVENT_TYPE_LOT_STARTED',
  LOT_UPDATED: 'AUCTION_EVENT_TYPE_LOT_UPDATED',
  BID_ACCEPTED: 'AUCTION_EVENT_TYPE_BID_ACCEPTED',
  BID_OUTBID: 'AUCTION_EVENT_TYPE_BID_OUTBID',
  BID_REJECTED: 'AUCTION_EVENT_TYPE_BID_REJECTED',
  RANKING_UPDATED: 'AUCTION_EVENT_TYPE_RANKING_UPDATED',
  TRUST_REVEALED: 'AUCTION_EVENT_TYPE_TRUST_REVEALED',
  DUEL_STARTED: 'AUCTION_EVENT_TYPE_DUEL_STARTED',
  DUEL_ENDED: 'AUCTION_EVENT_TYPE_DUEL_ENDED',
  LOT_SETTLED: 'AUCTION_EVENT_TYPE_LOT_SETTLED',
  LOT_CANCELLED: 'AUCTION_EVENT_TYPE_LOT_CANCELLED',
  ORDER_CREATED: 'AUCTION_EVENT_TYPE_ORDER_CREATED',
  PAYMENT_SUCCESS: 'AUCTION_EVENT_TYPE_PAYMENT_SUCCESS',
  AUCTION_EXTENDED: 'AUCTION_EVENT_TYPE_AUCTION_EXTENDED',
  AUCTION_CLOSED: 'AUCTION_EVENT_TYPE_AUCTION_CLOSED',
} as const satisfies Record<string, EventType>;

export const AUCTION_REFRESH_EVENTS = new Set<EventType>([
  REALTIME_EVENT.ROOM_SNAPSHOT,
  REALTIME_EVENT.LOT_CREATED,
  REALTIME_EVENT.LOT_STARTED,
  REALTIME_EVENT.LOT_UPDATED,
  REALTIME_EVENT.BID_ACCEPTED,
  REALTIME_EVENT.BID_OUTBID,
  REALTIME_EVENT.AUCTION_EXTENDED,
  REALTIME_EVENT.AUCTION_CLOSED,
  REALTIME_EVENT.LOT_SETTLED,
  REALTIME_EVENT.LOT_CANCELLED,
  REALTIME_EVENT.ORDER_CREATED,
  REALTIME_EVENT.PAYMENT_SUCCESS,
]);

export const ORDER_REFRESH_EVENTS = new Set<EventType>([
  REALTIME_EVENT.AUCTION_CLOSED,
  REALTIME_EVENT.LOT_SETTLED,
  REALTIME_EVENT.ORDER_CREATED,
  REALTIME_EVENT.PAYMENT_SUCCESS,
]);

export const REALTIME_CONSOLE_EVENTS = new Set<EventType>([
  REALTIME_EVENT.ROOM_SNAPSHOT,
  REALTIME_EVENT.LOT_STARTED,
  REALTIME_EVENT.LOT_UPDATED,
  REALTIME_EVENT.BID_ACCEPTED,
  REALTIME_EVENT.BID_OUTBID,
  REALTIME_EVENT.RANKING_UPDATED,
  REALTIME_EVENT.AUCTION_EXTENDED,
  REALTIME_EVENT.AUCTION_CLOSED,
  REALTIME_EVENT.TRUST_REVEALED,
  REALTIME_EVENT.DUEL_STARTED,
  REALTIME_EVENT.DUEL_ENDED,
  REALTIME_EVENT.LOT_SETTLED,
  REALTIME_EVENT.LOT_CANCELLED,
  REALTIME_EVENT.ORDER_CREATED,
  REALTIME_EVENT.PAYMENT_SUCCESS,
]);

export const HTTP_REFRESH_EVENTS = new Set<EventType>([
  REALTIME_EVENT.BID_ACCEPTED,
  REALTIME_EVENT.AUCTION_EXTENDED,
  REALTIME_EVENT.AUCTION_CLOSED,
  REALTIME_EVENT.ORDER_CREATED,
  REALTIME_EVENT.PAYMENT_SUCCESS,
]);
