CREATE TABLE IF NOT EXISTS auction_lots (
  id VARCHAR(64) PRIMARY KEY,
  room_id VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image_url VARCHAR(1024) NOT NULL,
  status INT NOT NULL,
  start_price_amount BIGINT NOT NULL,
  start_price_currency VARCHAR(16) NOT NULL,
  min_increment_amount BIGINT NOT NULL,
  min_increment_currency VARCHAR(16) NOT NULL,
  duration_seconds INT NOT NULL,
  anti_snipe_window_seconds INT NOT NULL,
  anti_snipe_extend_seconds INT NOT NULL,
  max_extend_count INT NOT NULL,
  current_price_amount BIGINT NOT NULL,
  current_price_currency VARCHAR(16) NOT NULL,
  leading_user_id VARCHAR(64) NOT NULL DEFAULT '',
  leading_nickname VARCHAR(128) NOT NULL DEFAULT '',
  started_at_unix_ms BIGINT NOT NULL DEFAULT 0,
  ends_at_unix_ms BIGINT NOT NULL DEFAULT 0,
  settled_at_unix_ms BIGINT NOT NULL DEFAULT 0,
  winner_user_id VARCHAR(64) NOT NULL DEFAULT '',
  winner_nickname VARCHAR(128) NOT NULL DEFAULT '',
  final_price_amount BIGINT NOT NULL DEFAULT 0,
  final_price_currency VARCHAR(16) NOT NULL DEFAULT '',
  version BIGINT NOT NULL,
  playbook_stage INT NOT NULL,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_room_status (room_id, status),
  INDEX idx_room_updated (room_id, updated_at),
  INDEX idx_status_ends_at (status, ends_at_unix_ms)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS auction_trust_cards (
  id VARCHAR(64) PRIMARY KEY,
  lot_id VARCHAR(64) NOT NULL,
  type INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  image_url VARCHAR(1024) NOT NULL,
  revealed TINYINT(1) NOT NULL DEFAULT 0,
  revealed_at_unix_ms BIGINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_lot_revealed (lot_id, revealed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS auction_bids (
  id VARCHAR(64) PRIMARY KEY,
  lot_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  nickname VARCHAR(128) NOT NULL,
  amount BIGINT NOT NULL,
  currency VARCHAR(16) NOT NULL,
  created_at_unix_ms BIGINT NOT NULL,
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_lot_created (lot_id, created_at_unix_ms),
  INDEX idx_lot_amount (lot_id, amount),
  INDEX idx_lot_user (lot_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS auction_events (
  id VARCHAR(64) PRIMARY KEY,
  room_id VARCHAR(64) NOT NULL,
  lot_id VARCHAR(64) NOT NULL,
  type INT NOT NULL,
  occurred_at_unix_ms BIGINT NOT NULL,
  reason VARCHAR(512) NOT NULL DEFAULT '',
  payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_room_occurred (room_id, occurred_at_unix_ms),
  INDEX idx_lot_occurred (lot_id, occurred_at_unix_ms),
  INDEX idx_type_occurred (type, occurred_at_unix_ms)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
