- targets:
    - 127.0.0.1:18080
  labels:
    shard: "0"
    shard_name: stack-0
    role: backend
- targets:
    - 172.31.226.179:18080
  labels:
    shard: "1"
    shard_name: stack-1
    role: backend
- targets:
    - 172.31.234.151:18080
  labels:
    shard: "2"
    shard_name: stack-2
    role: backend
